# Change these first
owner: dpi0 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Blog
    url: https://dpi0.cloud
  # - name: Forge
  #   url: https://git.dpi0.cloud
  - name: URL Shorterner
    url: https://k.dpi0.cloud
  - name: Imgur
    url: https://img.dpi0.cloud
  - name: Redlib
    url: https://r.dpi0.cloud
  - name: Bin
    url: https://bin.dpi0.cloud
  # - name: 4get
  #   url: https://4.dpi0.cloud

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dpi0.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: Uptime for **https://APP.dpi0.cloud**
  introMessage: Uptime status my blog and for some services hosted by [me](https://github.com/dpi0)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
